# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9592ac48946acaa7d5a4f7aa5e975b83ce304ac6d46a8919b1dbe2b257b44c9eb1fa9d5ebba117dda2088f4ec6c5984e84e5681918b80c85e9cead9ee02547f

test:
  secret_key_base: de517ea413f4fa65bfccaf824bb6b052040093f65730ea2b5f759631a688f79142f639d271d6a3279379fd4018b9b210414dc0c3516a26802e7d1362f1df14b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
